## Análisis de riesgo financiero

### Librerías

In [2]:
import pandas as pd
import duckdb
import os
import matplotlib.pyplot as plt

Se genera la lista de archivos

In [3]:
data_folder = 'data'

tables = os.listdir(data_folder)

files = {}
for t in tables:
    if t[-3:] == 'csv':
        files[t[:-4]] = t

Se cargan las tablas en duckdb con persistencia en el archivo financial_data.ducdb

In [4]:
conn = duckdb.connect('data/financial_data.duckdb') # o duckdb.connect('____.duckdb') para persistir

for table, file in files.items():
    try:
        conn.execute(f"""
            CREATE TABLE {table} AS 
            SELECT * FROM read_csv_auto('data/{file}')
        """)
    except:
        print('Hubo error en la carga de tablas o las tablas ya han sido cargadas')

# Verificar qué tablas quedaron cargadas
conn.execute("SHOW TABLES").fetchdf()

                  name
0       credit_history
1            customers
2    financial_profile
3    loan_applications
4       loan_decisions
5    new_loan_outcomes
6            new_loans
7  new_payment_history
8      payment_history
9       previous_loans

Se pueden ejecutar consultas SQL con el método execute de la conexión o con jupysql directamente escribiendo SQL con la cabecer %%sql y df << para asignar el resultado a un dataframe de pandas

In [5]:
conn.execute(
    f"""
    SELECT * FROM customers LIMIT 5;
    """
).fetchdf()

   customer_id birth_date  gender   education marital_status  dependents
0            1 1975-12-31  Female  University        Married           0
1            2 1973-12-31  Female   Secondary         Single           2
2            3 1983-12-31  Female   Secondary       Divorced           0
3            4 1987-12-31  Female   Secondary        Married           2
4            5 1975-12-31  Female   Secondary         Single           0

Se trabajará con jupysql para instalar utilizar: pip install jupysql duckdb-engine.

A continuación la carga de la librería, la configuración para obtener dataframes de pandas como salida de los quieries y suprimir mensajes

Finalmente se asocia la conexión de duckdeb con sql

In [8]:
%load_ext sql

%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

%sql conn --alias duckdb

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [9]:
%%sql
SELECT * FROM customers LIMIT 5;

   customer_id birth_date  gender   education marital_status  dependents
0            1 1975-12-31  Female  University        Married           0
1            2 1973-12-31  Female   Secondary         Single           2
2            3 1983-12-31  Female   Secondary       Divorced           0
3            4 1987-12-31  Female   Secondary        Married           2
4            5 1975-12-31  Female   Secondary         Single           0